
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: "This is an AWS Lambda function that collects CloudWatch logs and sends them to Logz.io in bulk, over HTTP."
Parameters:
  LogzioURL:
    Type: "String"
    Description: "Logz.io listener URL. If you are in the EU region insert 'https://listener-eu.logz.io:8071'. Otherwise, use 'https://listener.logz.io:8071'"
  LogzioTOKEN:
    Type: "String"
    Description: "Logz.io account token."

Resources:
  LogzioCloudwatchLogsCollector:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python2.7
      Handler: lambda_function.lambda_handler
      CodeUri: .
      FunctionName: logzio-cloudwatch-log-shipper
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          URL: !Ref LogzioURL
          TOKEN: !Ref LogzioTOKEN
          TYPE: 'YOUR-LOG-TYPE'
          FORMAT: 'YOUR-LOG-MESSAGE-FORMAT'